import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs'
import Appbar from "@/components/Appbar";

// import { Providers } from "@/components/Providers";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
   
       
         
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl text-green-600 bg-slate-100">Loading ..............</div>
          </ClerkLoading>
          <ClerkLoaded>
        {children}
        </ClerkLoaded>
      </body>
     
     
     
    </html>
    </ClerkProvider>
   
  );
}
